Move archive/* to the root to fix 404 errors
eiffel-community/eiffel-community.github.io pull request #45
Opened 2023-02-27 13:22 UTC by magnusbaeck

### Applicable Issues
#37 

### Description of the Change
The archived summit pages in the archive directory have never rendered properly since they contained relative URLs to e.g. js/csi.min.js. Let's just move the archived files back to the root of the repo. We won't have that many summits that the number of files will be overwhelming.

PR in action:
- https://magnusbaeck.github.io/eiffel-community.github.io/summit-2019-2.html
- https://magnusbaeck.github.io/eiffel-community.github.io/summit-2020-1.html
- https://magnusbaeck.github.io/eiffel-community.github.io/summit-2021-1.html

### Alternate Designs
Changing the relative URLs to match the directory layout (e.g. ../js/csi.min.js) works for the most part, but the relative URLs inside the included HTML files still won't work since they're evaluated against the including page's URL and not the included file's URL. Obviously, a relative URL reference can't possibly work for both /foo.html and /archive/foo.html.

Changing to absolute URLs will break user's GitHub Pages, i.e. https://myusername.github.io/eiffel-community.github.io/foo.html.

### Benefits
Archived summit pages render properly.

### Possible Drawbacks
In ten years' time the root directory might feel crowded with summit pages.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I    have the right to submit it under the open source license    indicated in the file; or

(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under a different license), as indicated    in the file; or

(c) The contribution was provided directly to me by some other    person who certified (a), (b) or (c) and I have not modified    it.

(d) I understand and agree that this project and the contribution    are public and that a record of the contribution (including all    personal information I submit with it, including my sign-off) is    maintained indefinitely and may be redistributed consistent with    this project or the open source license(s) involved.

Signed-off-by: Magnus Bäck \<magnus.back@axis.com>

2023-02-27 15:26 UTC, e-backmark-ericsson requested changes

2023-02-27 15:26 UTC, e-backmark-ericsson commented on summit-2021-1.html
> +    <link rel="apple-touch-icon" sizes="180x180" href="nimages/favicon/apple-touch-icon.png">
```suggestion
    <link rel="apple-touch-icon" sizes="180x180" href="images/favicon/apple-touch-icon.png">
```

2023-02-28 07:26 UTC, e-backmark-ericsson approved these changes

2023-02-28 11:16 UTC, t-persson approved these changes

2023-02-28 11:20 UTC, merged